Remove redefinition of FontAwesome
This resulted in a conflict with misleading symptoms (looking like file
not found):

(./fontawesome.sty
kpathsea: Running mktextfm FontAwesome
/usr/share/texmf-dist/web2c/mktexnam: Could not map source abbreviation F for FontAwesome.
/usr/share/texmf-dist/web2c/mktexnam: Need to update /usr/share/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input FontAwesome
This is METAFONT, Version 2.7182818 (TeX Live 2019/Arch Linux) (preloaded base=mf)

kpathsea: Running mktexmf FontAwesome
! I can't find file `FontAwesome'.
<*> ...our; mag:=1; nonstopmode; input FontAwesome

Please type another input file name
! Emergency stop.
<*> ...our; mag:=1; nonstopmode; input FontAwesome

Transcript written on mfput.log.
grep: FontAwesome.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input FontAwesome' failed to make FontAwesome.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Package fontspec Error: The font "FontAwesome" cannot be found.

For immediate help type H <return>.
 ...

l.14 \newcommand
                *{\faicon}[1]{{
?